### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuuritaly** [SekouD/mlconjug#61]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design for free a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by SekouD** [comment]
Hi Zuur.

That is so nice to hear from you!

I will definitely need any help you can afford to work with me.
I  have absolutely zero graphics design skills.

I am a developer/researcher at the University of Bordeaux Montaigne and just finished my master in Natural Language Processing and Understanding, so you see i have really no skill in graphics at all.

Even though I try to make this project attractive. I very often release updates and I have already translated the full documentation of the project API and have taken care of having the UI in 6 languages.

There is also a website I am working on that integrates mlconjug so that any body in the world can conjugate with machine learning for free.

I am very interested by offer. especially for the logo for now. a cute little robot with glasses ha :)

You should contact me to tell me more.

**Comment by zuuritaly** [comment]
Hello @SekouD  ,
Usually after the project owner accepts that I design the logo, I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by SekouD** [comment]
Hi Zuur.

Thanks for the reply.

Well as the project is about a Machine Learning library, I would imagine some cute little robot with glasses, kind of like an old grammar professor.
I don't want anything very specific, you have full artistic freedom.
I like blue and black, so it would be nice if you could incorporate some of it in the design.

That's a very great offer Zuur. I am sure I will like anything you can come up with.

I hope you will have free time enough to do the design. I will credit you on the website for sure!

Have a good day.

SekouD.

**Comment by zuuritaly** [comment]
Hello, I made this 2 designs for this project.

What do you think?

![mlconjug](https://user-images.githubusercontent.com/40405175/41814948-7f25357a-7754-11e8-8278-fd5075333518.png)

**Comment by SekouD** [comment]
Hi, That is pretty cool!

Thanks very much, that is really awesome!

I like the design, I am impressed!

Is it possible to have the 4th design? 

Thanks so much.

**Comment by zuuritaly** [comment]
Thanks for the words that means a lot for me, since Im a beginner.

I will make a pull request with the logo and logomark.

Best regards!

Zuur.

**Comment by SekouD** [comment]
Thanks Man, I really appreciate it!
